[tool.black]
line-length = 119
extend-exclude = "api/alembic"

[tool.isort]
profile = "black"
py_version = 39
skip_gitignore = true
line_length = 119
use_parentheses = true
include_trailing_comma = true