name: Create and publish a Docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  BASE_IMAGE: 'python:3.9-slim'
  BASE_IMAGE_PLATFORMS: 'linux/amd64,linux/arm64/v8'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        id: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release metadata
        id: get_release_metadata
        run: |
          release_tag=${{ steps.get_release.outputs.tag_name }}
          release_version=$(echo $release_tag | cut -c2-)
          image_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=release_version::$release_version"
          echo "::set-output name=release_tag::$release_tag"
          echo "::set-output name=image_name::$image_name"
          release_commit=$(git rev-list --count HEAD)
          echo "::set-output name=release_commit::$release_commit"
          build_date=$(date "+%F")
          echo "::set-output name=build_date::$build_date"

      - name: Build and push release
        id: docker_build_release
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/GHActions_Dockerfile
          platforms: ${{ env.BASE_IMAGE_PLATFORMS }}
          push: true
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            BUILD_DATE=${{ steps.get_release_metadata.outputs.build_date }}
            IMAGE_VERSION=${{ steps.get_release_metadata.outputs.release_version }}
            GIT_COMMIT=${{ steps.get_release_metadata.outputs.release_commit }}
            RELEASE_TAG=${{ steps.get_release_metadata.outputs.release_tag }}
          tags: |
            ghcr.io/${{ steps.get_release_metadata.outputs.image_name }}:latest
            ghcr.io/${{ steps.get_release_metadata.outputs.image_name }}:${{ steps.get_release_metadata.outputs.release_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
